<?php

namespace AppBundle\Repository;

/**
 * ImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImgRepository extends \Doctrine\ORM\EntityRepository
{
}
